### PR TITLE
Allow attaching to connenctivity events to be disabled.

### PR DESCRIPTION
**Pull request by alexjeffburke**

### CODE REVIEW

**Comment by alexjeffburke** [comment]
Hey,

Thanks for getting back to me so quickly! :)

Happy to write that bit of documentation, but let me explain the rationale - we are running a browser on an embedded system. We use a web socket to communicate with the firmware of the device, and lack of an internet connection doesn't actually imply the firmware has gone away. I think this might also help in local proxy type situations.

If there's anything else I can do to iterate on this do let me know.

Thanks, Alex.

**Comment by alexjeffburke** [comment]
I've document the new flag - have tried to make it clear that this isn't something for the normal case :)

**Comment by nathanboktae** [comment]
That makes sense. Nice PR! @taiga418 this PR looks good.

**Comment by pierrefourgeaud** [comment]
Is there anything blocking this change to be merged ? It would be really nice to have this as a released version :)

**Pull request merged**
